### ISSUE TITLE
After install ckeditor wiki without style

### ISSUE THREAD

**Issue by atvirasvilnius** [paginagmbh/redmine_lightbox2#49]
![image](https://user-images.githubusercontent.com/12123428/33373702-c50fa64c-d50b-11e7-8bec-daf8f086d1f9.png)

hi after install wiki page is terribable

**Comment by tofi86** [comment]
Hi, can you please remove my plugin and test whether the issue disappears and the page is formatted correctly? I want to make sure that it's an issue between my plugin and ckeditor and want to be sure which plugin causes the error before I start investigating. Thanks.

**Comment by atvirasvilnius** [comment]
When I swich off text formating Ckeditor formating come back ;)

![image](https://user-images.githubusercontent.com/12123428/33737449-ce04ab46-db9e-11e7-9372-6b23752a4008.png)



![image](https://user-images.githubusercontent.com/12123428/33737373-93261708-db9e-11e7-82a4-df8f8e83a51e.png)

![image](https://user-images.githubusercontent.com/12123428/33737480-e6fa96f6-db9e-11e7-8365-1da33b909512.png)

**Comment by tofi86** [comment]
So why do you think my plugin is the problem? You have more than 20 other plugins installed?!
My plugin does not apply nor change text formatting...

Again, please do the following:
1. leave text formatting option as is
2. uninstall my plugin
3. check your wiki page. is the formatting still wrong? or is the formatting correct?
4. install my plugin again
5. check your wiki page. is the formatting still wrong? or is the formatting correct?

**Comment by atvirasvilnius** [comment]
OK
1. done
2. done
3.  now format is correct (markdown):
![image](https://user-images.githubusercontent.com/12123428/33755718-d4dcdcca-dbfa-11e7-8d97-09ee70c48726.png)
4. install plugin again step by step
5. when I active in settting ckeditor format is missing:
![image](https://user-images.githubusercontent.com/12123428/33755855-6b309f68-dbfb-11e7-9608-4d2f1e7c2720.png)
6. remove other plugins:
![image](https://user-images.githubusercontent.com/12123428/33755887-919a1a08-dbfb-11e7-80b1-90d1ef06e2e2.png)

**Comment by tofi86** [comment]
Sorry for the late reply.

This has nothing to do with the lightbox plugin. You tested the wrong order. You should have tested the CKEditor plugin WITHOUT every other plugin but WITH my plugin. If you then disable the lightbox plugin nothing happens  and you will see that this is the default behaviour (plain text without markup).

You cannot switch the markup language in an existing Redmine installation without loosing all the existing markup.

When you used Markdown before and you have 500 wiki pages with Markdown syntax and you switch to CKEditor style now, all the 500 wiki pages are corrupted forever because you switched off Markdown support in Redmine in favour of CKEditor HTML styling.

The same will happen if you edit pages now in CKEditor. The editor saves the content as HTML and if you ever switch back to Markdown, all the CKEditor content is displayed wrong.

Read this thread on redmine.org: http://www.redmine.org/issues/22005
