### ISSUE TITLE
wrong message in plugins page

### ISSUE THREAD

**Issue by mmiat** [paginagmbh/redmine_lightbox2#69]
i've redmine 3.4.x, in plugins page lightbox2 shows there is an update (0.5.0) but last supported version is 0.4.4

**Comment by tofi86** [comment]
That's unfortunately an issue with the Redmine Plugin Repository, but let me explain:

I maintain different versions of this plugin for different Redmine versions:

* v0.4.x is for Redmine 3.4 and below
* v0.5.x is for Redmine 4.x

<img width="455" alt="Bildschirmfoto 2019-09-25 um 15 32 14" src="https://user-images.githubusercontent.com/365118/65605690-d5be5b00-dfa9-11e9-95b8-29656f682ed6.png">

Now if I mark v0.5.x only compatible with Redmine 4.x, the Redmine Plugin Repository is not able to tell, that other versions of the plugin still are compatible with Redmine 3.4. That's why I have to mark ALL compatible redmine versions in the Plugin Repo for the latest release.

The Plugin update check in the admin area can't distinguish either.

I'm sorry, this is best *I* can do.

**Comment by mmiat** [comment]
exactly, but in redmine 3.4.11 > admin > plugin it says that there is a new version for 0.4.4

**Comment by tofi86** [comment]
Yes. If you hover the update info it says there is 0.5.0 as an update. And that's because I have to label 0.5.0 as compatible with Redmine 3.4 although you'd have to use 0.4.4
