### ISSUE TITLE
Thumbnails in the attachment column table of all tasks

### ISSUE THREAD

**Issue by Milord-Freeman** [paginagmbh/redmine_lightbox2#76]
_This question was asked earlier on the [official redmine forum](http://www.redmine.org/boards/2/topics/58342). I apologize if this was incorrect._

Is there any way to display thumbnails in the "attachment" column on the page with a table of all tasks? Now a link to the file is displayed there [(an object of the "attachment" class)](https://user-images.githubusercontent.com/23146879/70698094-d082c980-1cd7-11ea-96c5-1ffb0083f17d.png), I had suggestions that it is possible to change the thumbnail in the controller that generates the table [(an object of the "attachment thumbnails" class)](https://user-images.githubusercontent.com/23146879/70698380-6880b300-1cd8-11ea-9d74-3ce836f22189.png), but I do not want to make changes to the plugin code if it’s theories can be made by the developer, because I'm not sure if this will be safe for full functionality / compatibility. If for some reason this is not possible, I will try to fork the project and make the changes myself.
I would be grateful for any information on the topic.

**Comment by tofi86** [comment]
hi @Milord-Freeman, thanks for your suggestion and sorry for the late reply.

I usually don't read the Redmine forum, only the plugin ratings and the GitHub issues.

It's quite easy to add the lightbox functionality to the attachement links, so I did that with commit dd5f80b on the `master` branch (requires Redmine 4.x). It's not yet released but you can install the plugin from the master sources and test it.

However, I did not implement a thumbnail view in the column because it would interfere in situations where you have a) lots of attachments on a ticket or b)  different file formats where some need to be displayed with a thumbnail and others don't. Both cases are a usability nightmare... 😅  so I decided not to implement this, I hope you can understand the decision.

I'm looking forward to your feedback! :-)

**Comment by Milord-Freeman** [comment]
Thank you for the answer at my request, the functionality that was requested by my management was rude and quickly implemented [here](https://github.com/Okatawa/redmine_lightbox2/commit/bfdfde5881f2d4130ea660663e1388d6268cdb3d) and [here](https://github.com/Okatawa/redmine_lightbox2/commit/f252b19fc26e14596f963730e26a0a95847f489f) in this fork. It is not so clean and correct, but it works, and for now I am using this solution. But I’m also interested in testing your version on a separate test assembly.
Upd: I agree that adding file thumbnails to a large list of tasks clutters the page and does not make sense, but this was the main requirement of my colleagues, and it seemed to them a very convenient opportunity. I think it would be wise to provide a choice of the thumbnail display mode in the list in the plugin settings.
